### Listar Musicas
GET https://localhost:7016/api/musica/listar

### Cadastrar Musicas
POST https://localhost:7016/api/musica/cadastrar
Content-Type: application/json

{
    "Titulo" : "Basket Case",
    "Artista" : "Green Day",
    "Album" : "Dookie",
    "AnoLancamento" : 1994,
    "UsuarioId" : 2
}

### Deletar Musicas
DELETE https://localhost:7016/api/musica/deletar/1
